
services:
  frontend:
    build:
      context: .
      args:
        VITE_KAKAO_MAP_API_KEY: ${VITE_KAKAO_MAP_API_KEY}
    ports:
      - "80:80"
    #environment:
    #  - VITE_KAKAO_MAP_API_KEY=${VITE_KAKAO_MAP_API_KEY}