version: '3'
services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_REACT_APP_KAKAOMAP_KEY=${VITE_REACT_APP_KAKAOMAP_KEY}

  # 백엔드 서비스는 나중에 추가할 수 있습니다
  # backend:
  #   build: ./backend
  #   ports:
  #     - "8080:8080"