
services:
  frontend:
    build:
      context: .
      args:
        VITE_KAKAOMAP_KEY: ${VITE_KAKAOMAP_KEY}
    ports:
      - "80:80"
    environment:
      - VITE_KAKAOMAP_KEY=${VITE_KAKAOMAP_KEY}