name: Commit Lint

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --ignore-engines --ignore-scripts --frozen-lockfile

      - name: Lint Commits
        run: |
          # 공통 조상 찾기
          BASE_SHA=$(git merge-base origin/${{ github.base_ref }} HEAD)
          HEAD_SHA=$(git rev-parse HEAD)
          
          # commitlint 실행
          npx commitlint --from=${BASE_SHA} --to=${HEAD_SHA} --config ./.config/.commitlintrc.cjs
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
          
          # commitlint 실행
