name: Commitlint
on:
  push:
    branches: [main, dev]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install -g @commitlint/cli @commitlint/config-conventional
      - name: Copy commitlint config
        run: cp .commitlintrc.cjs commitlint.config.js
      - name: Lint new commits
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            git log ${{ github.event.before }}..${{ github.event.after }} --format="%H" | xargs -I {} sh -c 'git show -s --format=%B {} | commitlint'
          fi