name: Commit Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run commitlint
        run: |
          yarn add -D @commitlint/config-conventional @commitlint/cli
          npx commitlint --from=$(git merge-base origin/$(echo ${GITHUB_REF#refs/heads/}) HEAD) --to=HEAD
