name: Docker Build and Local Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: |
        echo "VITE_KAKAOMAP_KEY=${{ secrets.VITE_KAKAOMAP_KEY }}" > .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: local-test-image:latest

    - name: Run Docker container
      run: |
        docker stop local-test-container || true
        docker rm local-test-container || true
        docker run -d --name local-test-container -p 80:80 -e VITE_KAKAOMAP_KEY=${{ secrets.VITE_KAKAOMAP_KEY }} local-test-image:latest

    - name: Check if container is running
      run: |
        docker ps
        curl http://localhost:80 || echo "Failed to reach the application"